apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - anonymax.dev
    secretName: hello-app-tls
  rules:
  - host: "anonymax.dev"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: api
              port:
                number: 80